"""
Django settings for bookmanager project.

Generated by 'django-admin startproject' using Django 1.11.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#1. __file__   当前的文件是 settings.py

# 2. os.path.abspath(__file__)  绝对路径
    # /home/python/Desktop/16/bookmanager/bookmanager/settings.py

#3. os.path.dirname(os.path.abspath(__file__))  directory 目录（文件夹）
    # /home/python/Desktop/16/bookmanager/bookmanager

#4. os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    #/home/python/Desktop/16/bookmanager

# 我们的所有web文件都是以 BASE_DIR 为相对路径
#os.path.join(BASE_DIR, 'templates')
# os.path.join  跨平台 文件的路径 window和 Linux mac 不一样
#
# base_dir + '/templates'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=2z3^8brmqw=j-+du&cw@%e_enm2f-q9g8e7339t=gfx(34s0x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
#我们需要在这里注册（安装）我们的子应用（flask中叫蓝图）
#暂时记住： 我们创建了子应用就需要在这里进行注册（安装）
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #子应用.apps.子应用名首字母大写Config
    'book.apps.BookConfig',
    'aaa.apps.AaaConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# 是我们工程的url的入口
# 默认是 工程中的 urls.py
# 程序的url入口是可以修改的，但是默认情况下 我们不修改
# ROOT_URLCONF = 'bookmanager.aaa'

ROOT_URLCONF = 'bookmanager.urls'

#模板的设置
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  #路径  os.path.join拼接路径
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bookmanager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        # 关系型数据库        ： mysql（中型）,oracle（大型）,sqlserver（中型）,sqlite3（小型）,db2(大型数据库IBM)
        # no-sql 非关系型数据库： redis
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),  # 拼接路径
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/
#语言设置
LANGUAGE_CODE = 'zh-Hans' #'en-us'
#时区
TIME_ZONE = 'Asia/Shanghai' #'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

# 我们访问静态文件的url是通过： http://ip:port +STATIC_URL + 文件名
STATIC_URL = '/enenen/'
# STATIC_URL = '/static/'

# 我们需要告知系统 static文件的路径
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static'),
]
